### ISSUE TITLE
trainByCrossValid fails for maxnet hinge feature classes

### ISSUE THREAD

**Issue by lysoifer** [adamlilith/enmSdm#139]
Hi,

I am trying to run trainByCrossValid for maxnet training. When hinge features are included in the classes, the function fails saying that it could not find the function 'hingeval'. The function works as long as hinge features are not included or if I manually load the 'hingeval' function from the maxnet package into the environment.

`mx = trainByCrossValid(data = pts, resp = 'presab', preds = 3:7, folds = pts$block, trainFx = 'trainMaxNet', regMult = seq(0.5,8,0.5), classes = 'lpqh', out = 'tuning')`
 `Modeling k = 1 on Mon Apr 25 09:51:25 2022...
Error in hingeval(hmean, 78.3085768563407, 91.973876953125) : 
  could not find function "hingeval"`

Thanks,
Lydia

**Comment by adamlilith** [comment]
Hi Lydia,

Thanks for bringing this to my attention.  The problem arises in the new predictMaxNet() function which I wrote to address issues with loading predict() for maxnet objects.  It should be fixed in the latest version of enmSdm (0.9.02).  I've tested trainByCrossValid() with maxnet/hinge features, so please let me know if it doesn't work.

Thanks again,
Adam
