### ISSUE TITLE
contBoyce produces convex P/E curve

### ISSUE THREAD

**Issue by carbonmetrics** [adamlilith/enmSdm#57]
I am sure I must be doing something wrong here, but my Maxent model produces a convex instead of a concave P/E curve, see image. 
I realise it is hard to say something without code, but does this look familiar?

![Rplot](https://user-images.githubusercontent.com/40055991/64768468-2bc6e380-d552-11e9-8c8d-85576c8469cc.png)

**Comment by adamlilith** [comment]
Thanks for the question... the x-axis on the left graph on the left indicates the expected proportion of presences in each bin _if_ the model had no ability to distinguish presences from non-presences.  In this case, for example, bin #97 (near the top on the left in the "P/E" plot) has a much higher proportion of presences in it than expected if presence predictions were randomly allocated across the landscape according to the prevalence of non-presences in that bin.  In other words, there are many more presences in bin #97 than you would expect if the model made predictions "randomly".  So the graph on the left is commensurate with the one on the right.

Since by default CBI is calculated with a rank correlation coefficient the shape (convex/concave) doesn't affect the outcome so long as the rank order of bins in the "CBI" plot or the "P/E/ plot is the same.  In other words, both graphs indicate that your model is good (or at least has a high CBI).

If this doesn't make sense, please feel free to ask.  I don't find CBI intuitive to explain, although I do find it intuitive to interpret (i.e., as a measure of how well a model's predicted probability of presence matched the observed probability of presence).
